raise Exception("I'm a failure!")